version: '3.9'

services:
  # Serviço PHP
  php:
    build:
      context: .  # Diretório onde está o Dockerfile
      dockerfile: Dockerfile  # Nome do Dockerfile
    container_name: php-container 
    ports:
      - "8080:80" 
    volumes:
      - ./www:/var/www/html
    depends_on:
      - db
    environment:
      COMPOSER_ALLOW_SUPERUSER: 1

  # Serviço MySQL
  db:
    image: mysql:8.0
    container_name: mysql 
    environment:
      MYSQL_ROOT_PASSWORD: marcio1015 
      MYSQL_DATABASE: gestao 
      MYSQL_USER: user 
      MYSQL_PASSWORD: marcio1015 
    ports:
      - "3406:3306" 
    volumes:
      - db_data:/var/lib/mysql

  # Serviço phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin 
    depends_on:
      - db
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: marcio1015 
    ports:
      - "8081:80" 

# Definição dos volumes
volumes:
  db_data: